# Generated by Django 3.2 on 2021-04-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fampayapp', '0002_auto_20210408_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='created',
        ),
    ]
